workspace:
  path: /mmm35

kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: node:12
    commands:
      - cd ./wp-content/themes/MMM35
      - npm ci
      - npm run build

  - name: publish
    when: 
      branch:
        - master
    image: appleboy/drone-scp
    settings:
      host: webyfssbz.wh.hosting.zone
      port: 2244
      username:
        from_secret: dev_ssh_user
      key:
        from_secret: dev_ssh_key
      source:
        - ./wp-content/themes/MMM35/*.php
        - ./wp-content/themes/MMM35/*.css
        - ./wp-content/themes/MMM35/*.png
        - ./wp-content/themes/MMM35/template-parts/*
        - ./wp-content/themes/MMM35/classes/*
      target: /home/webyfssbz/html/mmm35.b12f.io/wp-content/themes/MMM35/
      strip_components: 3
      rm: true
