workspace:
  path: /mmm35

kind: pipeline
type: docker
name: default
steps:
  - name: "Build theme"
    image: node:12
    commands:
      - cd ./wp-content/themes/MMM35
      - npm ci
      - npm run build

  - name: "Build plugin"
    image: node:12
    commands:
      - cd ./wp-content/mu-plugins/MMM35
      - npm ci
      - npm run build

  - name: publish-theme
    when: 
      branch:
        - master
    image: appleboy/drone-scp
    settings:
      host: webpxck7g.wh.hosting.zone
      port: 2244
      username:
        from_secret: dev_ssh_user
      key:
        from_secret: dev_ssh_key
      source:
        - ./wp-content/mu-plugins/MMM35.php
        - ./wp-content/mu-plugins/MMM35/MMM35.php
        - ./wp-content/mu-plugins/MMM35/blocks/*.php
        - ./wp-content/mu-plugins/MMM35/blocks/*/dist.js
        - ./wp-content/mu-plugins/MMM35/blocks/*/*.css
        - ./wp-content/mu-plugins/MMM35/blocks/*/dist.asset.php
        - ./wp-content/themes/MMM35/*.php
        - ./wp-content/themes/MMM35/*.css
        - ./wp-content/themes/MMM35/*.png
        - ./wp-content/themes/MMM35/*.js
        - ./wp-content/themes/MMM35/template-parts/*
        - ./wp-content/themes/MMM35/classes/*
        - ./wp-content/themes/MMM35/assets/*
      target: /home/webpxck7g/html/mmm35.b12f.io/
