version: '3.1'

services:
  wordpress:
    image: wordpress
    build: ./.docker/wordpress/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: $DB_HOST
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $DB_DATABASE
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/MMM35:/var/www/html/wp-content/themes/MMM35
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins

  theme-builder:
    image: node:12
    restart: unless-stopped
    command: npm start
    working_dir: /app
    volumes:
      - ./wp-content/themes/MMM35:/app
      - ./variables.scss:/app/variables.scss

  plugin-builder:
    image: node:12
    restart: unless-stopped
    command: npm start
    working_dir: /app
    volumes:
      - ./wp-content/mu-plugins/MMM35:/app
      - ./variables.scss:/app/variables.scss

  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
  wordpress:
